### ISSUE TITLE
Make + Add Category functionable

### ISSUE THREAD

**Issue by epsit03** [epsit03/ntc-lms#3]
### Abstract:

Login using `admin` and under the ADD BOOK page, I want the ```+ Add CATEGORY``` option functionable which must appear under the drop-down for kewords as it is. Basically, I want to add as many keywords as I want to...

### Working:

In the drop-down menu, as for now, two default kewords are there, *Computer* and *Programming*, and there is one more, **_+add Keyword_** but I want is that when I click on `+ Add CATEGORY`, it must give us a text-field to enter a keyword of our own choice, which when entered and pressed ***confirm!***, it adds that keyword to the drop-down too.

**Comment by omji74** [comment]
ok manupilate in dom

**Comment by epsit03** [comment]
Used the ```Dialog``` property from ```MaterialUI``` and it has assisted in giving prompt to user and take input. The only optimisation it needs is that the **ADD** button ain't working properly yet. Basically, it ain't sending the prompted text back the DB. Can you have a look at it?

**Comment by epsit03** [comment]
I enhanced the functionality but for its backend to work, there is a separate issue #7 is opened.
